# Generated by Django 6.0.3 on 2026-04-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_user_email_alter_user_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("To Do", "To Do"),
                    ("In Progress", "In Progress"),
                    ("Done", "Done"),
                ],
                default="To Do",
            ),
        ),
    ]
