# Generated by Django 6.0.3 on 2026-04-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Done", "Done"),
                    ("In Progress", "In Progress"),
                    ("To Do", "To Do"),
                ],
                default="To Do",
                max_length=20,
            ),
        ),
    ]
